### PR TITLE
WRR-4294: Updated ReadMe guide examples to reference Sandstone and removed any Moonstone references

### PR DESCRIPTION
**Pull request by paul-beldean-lgp**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [ ] I have run automated testing and it is passed
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Updated ReadMe guide

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Updated examples for components and themes to be ones available in Sandstone.
Updated the `serve` port to be 3000 because that is the default now.
Updated the view screenshots URL to be for `Sandstone-View`.
Removed `--pack-tests` example as it is no longer in the code and no longer works.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)
Changed Travis dist to `jammy` so that the Travis jobs would pass.

### Links
[//]: # (Related issues, references)
WRR-4294

### Comments

Enact-DCO-1.0-Signed-off-by: Paul Beldean paul.beldean@lgepartner.com

### CODE REVIEW

**Comment by seunghoh** [comment]
@paul-beldean-lgp Would you please update the title and the PR description for clarity?

**Review by stanca-pop-lgp — APPROVED** [review]
LGTM

**Comment by MikyungKim** [comment]
One thing I found is the mismatch styles like below.
image
Could you also make them look same?
It seems the same code but looks different.

**Review by MikyungKim — APPROVED** [review]
LGTM

**Pull request merged**
